### PR TITLE
Mark addresses used

### PR DESCRIPTION
**Pull request by tuxcanfly**
Added a database flag on Address to mark used addresses and prevent address re-use.

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks.  I took a very quick look and noticed that the serialization formation of addresses has been changed, but there is no code to upgrade the existing addresses which will be in the old format.

**Comment by tuxcanfly** [comment]
OK, didn't consider that since the integration branch is not on master, but I'll add it in case anyone is already using the branch.

**Comment by tuxcanfly** [comment]
Looks like build failed due to travis:

`An error occurred while compiling the build script: Travis::Shell::Generator::TaintedOutput` 

A forced rebuild should set this back to green.

**Comment by tuxcanfly** [comment]
Closing in favor of #196 which is based on intwaddrmgr instead of master

**Pull request closed without merging**
