### PR TITLE
build(deps): bump golang.org/x/crypto from 0.0.0-20200622213623-75b288015ac9 to 0.1.0 and fix linter

### PR DESCRIPTION
**Pull request by guggero**
Replaces https://github.com/btcsuite/btcwallet/pull/849 and also fixes a linter deprecation warning.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Needs a rebase.

**Comment by chappjc** [comment]
Might as well bump to v0.7.0 for golang.org/x/crypto now.  The Go team have been tagging a lot recently.

**Comment by guggero** [comment]
Rebased and also bumped both `golang.org/x/crypto` and `golang.org/x/net` to the latest versions.

**Review by Roasbeef — APPROVED** [review]
LGTM

**Pull request merged**
