### PR TITLE
Debug log the reason of connection failure

### PR DESCRIPTION
**Pull request by bclermont**
To let user run with more detailed debug log and figure why it fail

### CODE REVIEW

**Comment by bclermont** [comment]
I just spent a while trying to change user, pass, address and so on and I had to change the code to figure what I was doing wrong

**Comment by davecgh** [comment]
I think it's probably fine to include the error in the message regardless of the debug level.

For example:
```Go
log.Warnf("Connection to Bitcoin RPC chain server " +
				"unsuccessful -- available RPC methods will be "+
				"limited -- error: %v", err)
```

@jick any objections to that?

Alternatively, if the message is to be modified based on debug level, it would result in a cleaner message, in my opinion, to do it like so:

```Go
			msg := "Connection to Bitcoin RPC chain server unsuccessful -- "+
				"available RPC methods will be limited"
			if log.Level() <= btclog.DebugLevel {
				msg += "-- error: " + err.Error()
			}
			log.Warn(msg)
```

**Comment by jrick** [comment]
@dajohi those seem fine

**Comment by jick** [comment]
Hey, I'm afraid you've got the wrong e-mail address for somebody here.

Zack

**Comment by davecgh** [comment]
@jick:  Sorry was a typo.  I meant to put @jrick.

**Comment by bclermont** [comment]
Updated based on @davecgh comments

**Comment by davecgh** [comment]
OK

**Comment by jrick** [comment]
I'm not sure why this never got merged (sorry!) but the latest code keeps looping forever trying the connection (instead of stopping after 5 attempts or so like before) and logs an error for each unsuccessful attempt.

**Comment by jick** [comment]
Guys, I'm still not the right Zack Johnson.  Please remove my address from
this list.

**Pull request closed without merging**
