### PR TITLE
Add Makefile, use golangci-lint

### PR DESCRIPTION
**Pull request by guggero**
This PR aims to improve the tooling of the project by introducing a `Makefile` that offers goals for the most common tasks (formatting, linting, running unit tests) associated with development.

We also use a more sophisticated linter that's proven to be useful in the `lnd` project over the last 2 years or so.

After fixing all issues discovered by the linter, we can now also use the new `make` commands directly in the Travis CI script.

cc @wpaulino, @Roasbeef

### CODE REVIEW

**Review by Roasbeef — APPROVED** [review]
LGTM 🌲

I wonder if we should also move to Github actions like the other projects...can be done at a later time though, this'll at least let us unbork the current build.

**Comment by guggero** [comment]
I can add the GH scripts any time, just wasn't sure if the `btcsuite` org was already set up for paid GH services? Or whether we have the permissions to set it up that way?

**Review by wpaulino — APPROVED** [review]
LGTM, looks like we need to remove goveralls though?

> 10.39s$ make goveralls
 Fetching goveralls.
go get -u github.com/mattn/goveralls
go: downloading github.com/mattn/goveralls v0.0.8
go: github.com/mattn/goveralls upgrade => v0.0.8
go: downloading golang.org/x/tools v0.0.0-20200522201501-cb1345f3a375
go: golang.org/x/tools upgrade => v0.1.0
 Sending coverage report.
/home/travis/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
Makefile:101: recipe for target 'goveralls' failed
make: *** [goveralls] Error 1

**Comment by Roasbeef** [comment]
@wpaulino Yeah I saw that goveralls thing, I think it'll be resolved once things are merged perhaps?

**Comment by Roasbeef** [comment]
Actually we need to add it to the base goveralls install. I don't have the org-level permissions to do this, so I can do it in a follow up commit after this is merged, or we can tack it onto #733 @wpaulino.

**Pull request merged**
