### PR TITLE
Updates for btcjson type changes.

### PR DESCRIPTION
**Pull request by jrick**
To increase compatibility with Bitcoin Core Wallet, additional fields
were added to and other fields made optional for the listtransactions
and gettransaction results structs.  For both, fee was changed to be
optional (including the zero value is allowed).

Requires btcsuite/btcd#427

### CODE REVIEW

**Comment by davecgh** [comment]
[btcrpcclient](https://github.com/btcsuite/btcrpcclient) will need to be udpated as well.

**Comment by jrick** [comment]
You sure? It builds and works fine

**Comment by davecgh** [comment]
You're right.  I was thinking it was command updates for some reason.  Since it's only results, and there is no conversion happening for those results, it doesn't need an update.

**Comment by jrick** [comment]
needs review

**Comment by davecgh** [comment]
OK

**Pull request merged**
