### PR TITLE
Add sweepaccount tool.

### PR DESCRIPTION
**Pull request by jrick**
This tool creates on-chain transactions, one per used address in a
source account, to sweep all output value to new addresses in a
different destination account.

### CODE REVIEW

**Comment by jrick** [comment]
Example usage on testnet: http://sprunge.us/bKjh

**Comment by jrick** [comment]
Once #330 is in I'd like to use that to add testnet/simnet flags and normalize the rpc connection string (currently this requires the port, which could be made optional).

**Comment by jrick** [comment]
Added the new testnet and simnet options, and made the port in the rpc network address optional (uses the default mainnet/testnet/simnet wallet rpc server port if unspecified).

**Comment by jrick** [comment]
Also, AmountFlag looks useful for other tools and/or btcwallet itself.  Thoughts on moving that into cfgutil @davecgh?

**Comment by davecgh** [comment]
Personally, I'd just do it like dhill did in btcd where the exported config struct entry a float64 and then the conversion and error bits are in the `loadConfig` function.  Making it satisfy the go-flags interface more tightly integrates it to go-flags which I'd personally prefer to avoid.

That said, if you want to do it this way and put it over in `cfgutil`, that's fine too.  I don't have a strong opinion on it.

**Comment by jrick** [comment]
Actually I'd like to see the logic in UnmarshalFlag to be moved to btcutil.NewAmountFromString and check for other units besides BTC, and then the interface method just calls that.

Satisifying the go-flags interface makes sense at this point since we're committed to it and want to use it everywhere for consistency.  cfgutil is also an internal package so it only affects this repo.

**Comment by davecgh** [comment]
Improving `btcutil.NewAmountFromString` sounds like a fine idea to me.

**Comment by davecgh** [comment]
I like the idea of the utility, but I haven't reviewed the code yet.

**Comment by dajohi** [comment]
This tool worked great on both mainnet and testnet.  I just used it to move my funds from imported accounts to the new addresses on the chain.  Back in business.

**Comment by jrick** [comment]
Rebased over latest master and rewritten to use the new txauthor package to create the unsigned transaction.

**Comment by davecgh** [comment]
OK

**Comment by jrick** [comment]
Well turns out this wasn't rebased over master after all.  Merged as 4ee9ce59fba801ff5036de35afac67b61e6247cc.

**Pull request closed without merging**
