### PR TITLE
Votingpool review

### PR DESCRIPTION
**Pull request by gsalgado**
This is just a rebase of votingpool_review on top of the latest master

### CODE REVIEW

**Comment by jrick** [comment]
Thanks for the reminder about this.  We certainly want to get this reviewed and in.

This branch isn't mergable though.  I'm seeing many commits that are already on master in this PR.  Could you rebase it again without these?

**Comment by gsalgado** [comment]
My votingpool_review branch has no changes on top of what's on btcsuite/btcwallet's votingpool_review -- it's just a rebase of the latter on top of master. I think the best way forward is to push (-f) my votingpool_review to btcsuite/btcwallet and then create the PR from that to master

**Comment by jrick** [comment]
Yeah force pushing is fine in this case.

**Comment by jrick** [comment]
Oh, I see the issue. You're trying to merge your rebased branch into the votingpool_review branch in this repo, so it's replaying both new commits on master, and the same votingpool commits a second time.

I'll fetch your branch and force push it to the btcsuite repo.  Then the old PR will be updated with the latest code.

**Comment by jrick** [comment]
Wasn't there a PR which merged that review branch to master? I can't seem to find it.

If there's not, we should open one.

**Comment by davecgh** [comment]
It was merged to the `votingpool_review` branch, not master.

**Comment by jrick** [comment]
@davecgh that was intended. afaik none of us have reviewed these yet, so they're not ready for master.

**Pull request merged**
