### PR TITLE
invalid transaction hashes crashes btcwallet

### PR DESCRIPTION
**Pull request by gmelika**
this is for issue #404

### CODE REVIEW

**Comment by jrick** [comment]
Thanks for spotting this.  You're right that TxDetails will return a nil transaction and a nil error when the transaction is not found.

Since the error case is handled by returning "not found" to the caller, could you first check that the error is not nil, and encode the error to a string to report the error, and then check if txDetails is nil after the error check?

**Comment by gmelika** [comment]
separated the error messages based on your feedback.  I basically copied the error text from another place in the code that did that same check

**Comment by jrick** [comment]
Minor style nitpick: can you split the string over several lines (concatenating them with +) so this fits in under 80 columns?

FWIW this is not my preferred style and I admit to breaking it in some places for practical reasons (like the rpcserver package) but here there's no real reason not to keep it similar to the surrounding code.

**Comment by gmelika** [comment]
no problem.  I fixed it, and squashed the commits

**Comment by jrick** [comment]
Looks like you need to run go fmt on it.

**Comment by gmelika** [comment]
> meh, this looks simple enough to commit as is. what could possibly go wrong, anyway

- Anonymous developer 😄

**Pull request merged**
