### PR TITLE
legacyrpc: add address type arg to getNewAddress

### PR DESCRIPTION
**Pull request by chappjc**
Resolves https://github.com/btcsuite/btcwallet/issues/646 and https://github.com/btcsuite/btcwallet/issues/762
<s>Requires https://github.com/btcsuite/btcd/pull/1776 (see the `replace` to my btcd repository that would be removed if that is merged). The btcctl from that branch would also be needed for testing this.</s>

This handles the `AddressType` argument in the `getNewAddress` and `getRawChangeAddress` RPC handlers. It recognizes "legacy", "p2sh-segwit", and "bech32" to match Bitcoin Core's RPC options.  These correspond to the bip44, bip49 "plus", and bip84 paths.  These are the `waddrmgr.DefaultKeyScopes`.

The `validateaddress` RPC is already able to recognize these addresses, and it may be used to verify the addresses returned by both `getnewaddress` and `getrawchangeaddress`.

This adds `btcjson.ErrRPCWalletInvalidAddressType` with a code (-5) and message ("unknown address type") to match Bitcoin Core's v22.

### CODE REVIEW

**Comment by chappjc** [comment]
Updated `getrawchangeaddress` as well.

**Comment by chappjc** [comment]
Will rebase and resolve

**Comment by chappjc** [comment]
Go 1.18 didn't accept existing the t.Error issue in keystore.  I can pop that fix off this PR if you want but I can't pass unit test with Go 1.18 otherwise.

**Comment by chappjc** [comment]
Ready for CI again.  Sorry for the churn there, I had pushed a garbage test app.

**Comment by chappjc** [comment]
Removed the temporary `replace` and rebased.  I need to re-test on my end though.

CI is bombing now because it started using go 1.18 and `go get` works differently than it used to.  I think https://github.com/btcsuite/btcwallet/pull/800 is needed.

**Comment by chappjc** [comment]
All still working as expected on my end after rebasing.  Can get addresses of all three type and they validate as ismine.

**Comment by Roasbeef** [comment]
This slipped by, approved a CI run.

**Comment by chappjc** [comment]
Looks like I need to rebase. Also I'd fix up this PR if you would like to accept the btcjson changes proposed in https://github.com/btcsuite/btcd/pull/1844

**Comment by chappjc** [comment]
Now that btcd 0.23 is tagged with rpcclient using https://github.com/btcsuite/btcd/pull/1776, this PR will have to get merged before a new btcwallet release otherwise rpcclient will not be able to get new addresses from btcwallet.  See https://github.com/btcsuite/btcd/issues/1843

Also note I had proposed https://github.com/btcsuite/btcd/pull/1844 to make rpclient usable with older btcwallets too, but that's not merged.

**Comment by chappjc** [comment]
Just retested with the following commands:

```
getnewaddress
getnewaddress "default"
getnewaddress "default" "legacy"
getnewaddress "default" "p2sh-segwit"
getnewaddress "default" "bech32"
getrawchangeaddress "default" "legacy"
getrawchangeaddress "default" "p2sh-segwit"
getrawchangeaddress "default" "bech32"
```

All working as expected.

I had to update to neutrino 0.14.2 locally to build, but that is also done in https://github.com/btcsuite/btcwallet/pull/805

**Comment by Crypt-iQ** [comment]
I'll pull this into #805 and give commit credit once the neutrino upgrade issue is resolved

**Comment by Crypt-iQ** [comment]
Replaced by #805

**Pull request closed without merging**
