### PR TITLE
CI: fix Makefile not working with go 1.18

### PR DESCRIPTION
**Pull request by chappjc**
go get is no longer used to install or build things. Use go install
instead.  Also specify a version so the module's go.mod is not
touched when installing the CI tools.

### CODE REVIEW

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Comment by Roasbeef** [comment]
Approved for a CI run, should be automatic after this gets in (github new contributor clause).

**Comment by Roasbeef** [comment]
I wonder if we'll run into this here? https://github.com/golang/go/issues/44840

**Comment by guggero** [comment]
It looks like you need to use at least `golangci-lint v1.40.0` to get this fixed. But that will require a few of the new rules that were introduced in that version to be addressed as well.

**Comment by chappjc** [comment]
I'll update the linter and fix whatever.  Just a few and I'll be on it...

**Comment by chappjc** [comment]
Oh nevermind... https://github.com/btcsuite/btcwallet/pull/795#issuecomment-1102997537

**Comment by guggero** [comment]
> Oh nevermind... [#795 (comment)](https://github.com/btcsuite/btcwallet/pull/795#issuecomment-1102997537)

Actually, I just found your PR instead that aims to fix it. So I didn't start on a PR myself.

**Comment by chappjc** [comment]
Oh, haha, let me try latest golangci-lint locally and see what needs to update.

**Comment by chappjc** [comment]
Yikes it's a LOT, at least if you use the default enabled linters.  
To pass as-is needs `--disable errcheck,deadcode,unused,ineffassign,staticcheck,varcheck,structcheck`
I have a feeling most of those except perhaps `errcheck`, which is super annoying, are worth satisfying, but it looks to be a lot of work.

**Comment by chappjc** [comment]
But the few lint issues thrown by the current version of golangci-lint are fixed in https://github.com/btcsuite/btcwallet/pull/783/commits/1d1c00321dca8c396f1558665f2d3cc5d2118db6 (part of https://github.com/btcsuite/btcwallet/pull/783).

**Comment by guggero** [comment]
If a lot of errors come from the same (new) linter, I think an option might also be to disable the linter for now and then fix the issues in a later commit.

**Comment by chappjc** [comment]
K, lemme see how many would need to be disabled for btcwallet using golangci-ling 1.45.2, which I think is needed for go 1.18 practically

**Comment by guggero** [comment]
I tried and it looked like `v1.40.0` is the oldest version that actually compiles with golang 1.18.

**Comment by chappjc** [comment]
OK wow, I'd suggest whitelisting linters (--disable-all and selective --enable) instead of the blacklisting (--enable-all and selective --disable).  There are more than 20 linters (so far) that are going to be extremely difficult to satisfy.

Alternative, use the 10 default linters and add any extras you want `[deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]`

<details>
  <summary>just some that need to be disabled</summary>
```
    - errlint

    - paralleltest
    - exhaustive
    - nestif
    - gocognit
    - cyclop
    - tparallel
    - testpackage
    - gci
    - errname
    - godox
    - wrapcheck
    - varnamelen
    - gomnd
    - ifshort
    - ireturn
    - nilnil
    - nlreturn
    - stylecheck
    - goerr113
    - exhaustivestruct
 ```
</details>

**Comment by Roasbeef** [comment]
Approved another CI run...

**Comment by Roasbeef** [comment]
CI looking pretty good...

**Review by Roasbeef — APPROVED** [review]
LGTM 🏉

**Pull request merged**
