### PR TITLE
Rename some rpc commands to something more generic.

### PR DESCRIPTION
**Pull request by jcvernaleo**
StartBtcdRpc becomes StartConcensusRpc.

This is useful for forks such as decred or if someone were to write
another compatible server.

### CODE REVIEW

**Comment by jrick** [comment]
This needs to bump the api major version (to 1.0.0) since it is a breaking change.  The version is documented in api.md and declared in code in rpc/rpcserver/server.go.

**Comment by jcvernaleo** [comment]
Done.  Does paymetheus check the version somewhere?

**Comment by jrick** [comment]
Yes. https://github.com/btcsuite/Paymetheus/blob/ccbe725254cd6e7020c7f67b8aed8248a2a3ceea/Paymetheus.Rpc/WalletClient.cs#L23

**Comment by jrick** [comment]
ok after squash

**Comment by jcvernaleo** [comment]
Squashed.

**Comment by jrick** [comment]
Actually, this has a typo.  It should be Consensus, not Concensus.

**Comment by jcvernaleo** [comment]
Pushed a fixed one.  But really it is your fault for trusting me to spell something correctly.

**Pull request merged**
